// Assignment #3: smallsh
// Filename: smallsh.c
// Author: Paul Scrugham
// ONID #: 934308765
// Date Due: 2/7/2022

#include "smallsh.h"

int main(void)
{
	char* prompt = ": ";
	int sentinel = 1;
	pid_t childPid;
	int fgStatus = -1;
	int bgStatus;
	char* exitStatusMessage = "exit value";
	char* termStatusMessage = "terminated by signal";
	struct bgChildPIDs* bgChildList = NULL;

	// Initialize and install a signal handler for SIGINT
	struct sigaction SIGINT_action = { {0} };
	SIGINT_action.sa_handler = SIG_IGN;
	sigemptyset(&SIGINT_action.sa_mask);
	SIGINT_action.sa_flags = SA_RESTART;
	sigaction(SIGINT, &SIGINT_action, NULL);

	// Initialize and install a signal handler for SIGTSTP
	struct sigaction SIGTSTP_action = { {0} };
	SIGTSTP_action.sa_handler = sigtstpOn;
	sigemptyset(&SIGTSTP_action.sa_mask);
	sigaddset(&SIGTSTP_action.sa_mask, SIGTSTP);
	SIGTSTP_action.sa_flags = SA_RESTART;
	sigaction(SIGTSTP, &SIGTSTP_action, NULL);

	while (sentinel) {
		// Reset 
		char* inputString = NULL;
		size_t buflen = 0;

		// Non-blocking wait for background processes
		waitBG(childPid, bgStatus, bgChildList, exitStatusMessage, termStatusMessage);

		// Prompt user for input
		printf(prompt);
		fflush(stdout);
		fflush(stdin);
		getline(&inputString, &buflen, stdin);

		// Strip newline character generated by getline
		inputString[strcspn(inputString, "\n")] = 0;

		// After input is received, block SIGTSTP until foreground process has terminated
		sigprocmask(SIG_BLOCK, &SIGTSTP_action.sa_mask, NULL);

		// Check for empty or commented input string
		if (preParser(inputString) == 0) {
			continue;
		}

		// Declare the user input struct
		struct userInput* input;

		// Expand any occurrences of "$$" to the program's PID
		char* oldVar = "$$";
		int numVars = countStringInstances(oldVar, inputString);
		
		if (numVars > 0) {
			char* expandedInput = expandVar(inputString, numVars, oldVar);
			input = parseInput(expandedInput);
			free(expandedInput);
		}
		else {
			input = parseInput(inputString);
		}
		free(inputString);

		// Reset background if foreground only mode is on
		if (flag == 1) {
			input->background = 0;
		}

		// Check if command is a smallsh built-in
		if (strcmp(input->args[0], "exit") == 0) {
			// Clear background
			input->background = 0;
			// Catch any background processes and terminate them
			struct bgChildPIDs* curr = bgChildList;
			while (curr) {
				// Terminate process
				kill(curr->pid, SIGTERM);
				// Clean up dead process
				waitpid(curr->pid, &bgStatus, WNOHANG);
				curr = curr->next;
			}

			return EXIT_SUCCESS;
		}
		else if (strcmp(input->args[0], "cd") == 0) {
			// Clear background
			input->background = 0;
			// Run command
			cdBuiltIn(input->args[1]);

		}
		else if (strcmp(input->args[0], "status") == 0) {
			// Clear background
			input->background = 0;
			if (fgStatus == -1) {
				printf("%s %d\n", exitStatusMessage, 0);
				fflush(stdout);
			}
			else if (WIFEXITED(fgStatus)) {
				printf("%s %d\n", exitStatusMessage, WEXITSTATUS(fgStatus));
				fflush(stdout);
			}
			else if (WIFSIGNALED(fgStatus)) {
				printf("%s %d\n", termStatusMessage, WTERMSIG(fgStatus));
				fflush(stdout);
			}
		}
		// Run an arbitrary command
		else {
			childPid = runArbitrary(input);
			// Handle foreground execution
			if (!input->background) {
				waitpid(childPid, &fgStatus, 0);
				
				// Print termination status if terminated by SIGINT
				if (WIFSIGNALED(fgStatus)) {
					printf("%s %d\n", termStatusMessage, WTERMSIG(fgStatus));
					fflush(stdout);
				}
			}
			else {
				printf("background pid is %d\n", childPid);
				fflush(stdout);
				// Add child PID to array
				if (bgChildList) {
					// Add child to current list
					bgChildList = addChildPID(childPid, bgChildList);
				}
				else {
					// Start list
					bgChildList = createChildPID(childPid);
				}
			}
		}

		// After foreground processes have finished running, unblock SIGTSTP
		sigprocmask(SIG_UNBLOCK, &SIGTSTP_action.sa_mask, NULL);

		// free the user input struct
		free(input);
	}
	
	return EXIT_FAILURE;
}